### ISSUE TITLE
Every automatically downloaded upgrade fails to run. Claims the EXE now is an invalid picture file!

### ISSUE THREAD

**Issue by eirikora** [electron/fiddle#1043] opened 2022-04-15 12:57 UTC
I run Fiddle on a Windows 10 machine with Norwegian locale. Every now and then Fiddle claims it needs to restart to upgrade and every time it just will not restart. When I then try to start the Fiddle App from the start menu, I now get an error message claiming that the EXE file now is an invalid picture file for this type of machine. What?! 
I have tried to run different versions but have to run the last downloaded installer again to get back in. This is a serious issue.
I'm right now running this version: electron-fiddle-0.28.0-win32-x64-setup.exe, but had same issue for version 0.27.3.

Best regards,
Eirik

**Comment by erickzhao** [comment] 2022-04-15 16:19
Duplicate of #954

Sorry for the issues, we've been aware of it but a fix has not been pushed out 😬

**Closed by erickzhao** 2022-04-15 16:19 UTC
