### ISSUE TITLE
Feature Idea: Support i18n

### ISSUE THREAD

**Issue by normal-coder** [electron/fiddle#563] opened 2021-01-15 09:22 UTC
Is it possible for Fiddle to support i18n?
For many Electron developers and novices. If the Fiddle tool supports internationalization, it will be a great help for learning and working debugging.
In addition. Do we consider supporting internationalization in the project itself and calling everyone to participate in translation work through the community?

**Comment by ckerr** [comment] 2021-03-27 05:07
I believe this is a duplicate of #191

**Closed by ckerr** 2021-03-27 05:07 UTC
Labels: :sparkles: enhancement
