### ISSUE TITLE
Accelerators on dialogs button doesn't underline the key

### ISSUE THREAD

**Issue by MaelNivel** [electron/fiddle#1338] opened 2023-04-25 13:15 UTC
### Expected Behavior
Dialog buttons with accelerator underline the accelerator key on Windows.

#### Example of expected behavior:
![image](https://user-images.githubusercontent.com/127734549/234287203-f1c1de09-d45e-47f3-9515-943109597407.png)

### Actual Behavior
The dialogue buttons include the accelerator key but never highlight the required key.

#### Example of actual behavior:
![image](https://user-images.githubusercontent.com/127734549/234287473-4865c074-d78c-4f77-9d80-620a2c88c16d.png)

### Testcase Gist URL
https://gist.github.com/f194d4a646828412d9e2e406613695d2

**Comment by codebytere** [comment] 2023-04-25 13:29
This is a duplicate of https://github.com/electron/electron/issues/37563.

**Closed by codebytere** 2023-04-25 13:29 UTC
