### ISSUE TITLE
Close (X) button in Settings not focusable at all 

### ISSUE THREAD

**Issue by carolstran** [electron/fiddle#1090] opened 2022-05-26 21:48 UTC
When you go to any page in the Settings, there is an `X` that appears in the upper righthand corner. You can click that to exit this view, but it's not focusable at all when navigating with a keyboard. 

![Screenshot of the top of the Executions page. In the corner you can see a white X.](https://user-images.githubusercontent.com/26869552/170585459-83da5865-0944-45fc-8ddf-a785b21d44b1.png)

This is likely because the `X`, semantically speaking, is not a `button` when it likely should be 😬 

From `settings.tsx`:
```
<div className="settings-close" onClick={appState.toggleSettings}>
    <Icon icon="cross" iconSize={25} />
</div>
```

**Comment by Hanaffi** [comment] 2022-05-27 12:18
@codebytere Hey,
Coming from your tweet and referred by Keeley.
Can you please assign this to me?

**Comment by Hanaffi** [comment] 2022-05-27 12:52
@codebytere Hey,
Coming from your tweet and referred by Keeley (@VerteDinde)
Can you please assign this to me?

**Comment by VerteDinde** [comment] 2022-05-27 15:54
Hey @Hanaffi! Please feel free to just submit a PR for this if you’d like to work on it.

**Comment by Hanaffi** [comment] 2022-05-28 15:53
Sorry but my first time to play with Fiddle , What should I do after this?
Would it run on localhost or what? I dont see anything
![image](https://user-images.githubusercontent.com/35642947/170832938-f82290e9-cde8-4bfd-bc77-67af3b1c2627.png)

**Comment by BlackHole1** [comment] 2022-05-28 18:42
Local launch:

```shell
git clone git@github.com:electron/fiddle.git
cd fiddle
yarn install
yarn run start
```

**Comment by codebytere** [comment] 2022-05-28 18:44
@Hanaffi you can't run multiple versions of fiddle simultaneously - ensure you've quit all other instances before launching a local one.

**Comment by Hanaffi** [comment] 2022-05-28 19:08
@BlackHole1  Yes thats what I actually did.

@codebytere It only ran once. Could WSL2 be the cause of this problem?
I'm using windows10 and WSL2 for development. but wsl2 doesnt allow GUI windows I guess. Its just a terminal AFAIR.
![image](https://user-images.githubusercontent.com/35642947/170839542-070664e3-c1d7-4754-830e-470a33443c66.png)

**Comment by Hanaffi** [comment] 2022-05-29 01:56
Okk , It was WSL2 issue. handled it.

**Closed** 2022-06-01 08:28 UTC
Labels: :beetle: bug, good first issue, area:settings
