### ISSUE TITLE
Loading the fiddle failed: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by bohning** [electron/fiddle#905] opened 2021-11-17 16:20 UTC
Electron 16.0.0 (alternatively 13.1.7)
Electron Fiddle 0.26.0 (12.0.14)

Tested with several of these: https://www.electronjs.org/docs/latest/tutorial/examples
![image](https://user-images.githubusercontent.com/1497707/142239297-685a70af-639c-4772-9365-a98b6a9fb849.png)

**Comment by ckerr** [comment] 2021-11-17 17:58
Hey @bohning, thanks for reporting this.

I'm not able to reproduce this error. Do you have a specific URL that you're loading to repro this?

Also, could you try in Fiddle using Help > Toggle Developer Tools to find a backtrace for that error and paste it here in the ticket?

**Comment by erickzhao** [comment] 2021-11-17 18:42
@bohning do you happen to have a GitHub Personal Access Token set for Electron Fiddle? 🤔

**Comment by bohning** [comment] 2021-11-18 06:23
> Hey @bohning, thanks for reporting this.
> 
> I'm not able to reproduce this error. Do you have a specific URL that you're loading to repro this?
> 
> Also, could you try in Fiddle using Help > Toggle Developer Tools to find a backtrace for that error and paste it here in the ticket?

Thanks a lot for taking the time to get back to me. I’m entirely new to Electron, so most likely the problem is on my end...

I am on macOS Monterey (12.0.1). This is what I did:

1. `git clone https://github.com/electron/electron-quick-start`
2. `cd electron-quick-start`
3. `npm install && npm start`

This starts the Hello-World application just fine. Then I installed Visual Studio Code IDE

4. `brew install visual-studio-code` and pointed it to the electron-quick-start folder
5. added a run configuration with "npm start"

Then I was able to start/debug the Hello-World application from  the IDE just fine. Then I read on in the introduction about Fiddle and installed it via

6. `brew install electron-fiddle`

and started it via my launcher (Alfred). Hitting ’Run’ also launches the Hello-World application just fine. Electron 13.1.7 came with the brew installation, so I updated to the latest version 16.0.0 and tested the Hello-World application again, which still runs fine.

So now I was curious to try more advanced examples and clicked on several "Open in Fiddle" links in the [examples](https://www.electronjs.org/docs/latest/tutorial/examples), e.g. [https://fiddle.electronjs.org/launch?target=electron/v16.0.0/docs/fiddles/quick-start](https://fiddle.electronjs.org/launch?target=electron/v16.0.0/docs/fiddles/quick-start). The Fiddle window opens and asks me:

![image](https://user-images.githubusercontent.com/1497707/142362884-dfe455aa-df47-4ceb-a018-a907096f4561.png)

I confirm and then I get the error message in my first message of my issue. This is the same for all the "Open in Fiddle" links, no matter which one.

@ckerr: not exactly sure where to look in the developer tools, do you have a hint where to look?

![image](https://user-images.githubusercontent.com/1497707/142363299-8b87c4d3-5c58-46c8-886e-59a48b388988.png)

**Comment by ckerr** [comment] 2021-11-18 17:31
> @ckerr: not exactly sure where to look in the developer tools, do you have a hint where to look?

It's possible that the Devtools' "Console" tab will have a line in it somewhere with that error message, and that expanding that line will show a backtrace of the code that got called leading up to the crash.

Also,

> Thanks a lot for taking the time to get back to me. I’m entirely new to Electron, so most likely the problem is on my end...

Welcome! Since you're new, I want to drop a link here to [the Electron Discord server](https://discord.com/invite/electron) since that has a nice community of people using Electron who may be able to help answer questions as you start using Electron.

**Comment by bohning** [comment] 2021-11-18 19:42
Here’s the console output:
![image](https://user-images.githubusercontent.com/1497707/142485714-14bead16-024e-42de-b387-0377ad1d3c4d.png)

Thanks for the link to the Electron Dischord server!

**Comment by dsanders11** [comment] 2021-12-03 04:24
@bohning, this should be fixed in v0.27.2, could you try it out and confirm?

**Comment by bohning** [comment] 2021-12-03 07:33
@dsanders11 Indeed it is fixed, I just tested. Awesome, thanks a lot!

**Closed** 2021-12-03 15:18 UTC
Labels: :question: more-information-needed
